"""first migration

Revision ID: 799986945827
Revises: 
Create Date: 2021-08-14 15:18:48.150866

"""
import sqlalchemy as sa
from alembic import op

revision = '799986945827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), sa.Identity(always=True, cache=5), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
                    sa.Column('unit_price', sa.Numeric(precision=8), server_default='1', nullable=True),
                    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'VERY_LARGE', name='sizeenum'),
                              nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, cache=5), nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
                    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
                    sa.Column('phone_number', sa.Text(), nullable=True),
                    sa.Column('email', sa.VARCHAR(length=70), nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(length=100), nullable=True),
                    sa.Column('balance', sa.DECIMAL(), server_default='0', nullable=True),
                    sa.Column('username', sa.VARCHAR(length=70), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('orders',
                    sa.Column('order_id', sa.Integer(), sa.Identity(always=True, cache=5), nullable=False),
                    sa.Column('product_id', sa.SmallInteger(), nullable=True),
                    sa.Column('quantity', sa.SmallInteger(), server_default='1', nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    enum = sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'VERY_LARGE', name='sizeenum')
    enum.drop(bind=op.get_bind())
    # ### end Alembic commands ###
